
version: '2'

###
# Dev
###
services:
  
  ###
  # Font End NodeJS Application Server & Proxy
  ###
  video-service:
    build: .
    volumes:
      - ./lib:/service/lib
      - ./index.js:/service/index.js
      - ./service-account.json:/etc/fin/webapp-service-account.json
      - ./service-account.json:/etc/fin/service-account.json
      - storage:/storage
    ports:
      - 8090:8080
    command: tail -f /dev/null
    # command: node app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - SERVICE_NAME=${SERVICE_NAME}
volumes:
  storage:
    driver: local